apiVersion: redhatcop.redhat.io/v1alpha1
kind: Policy
metadata:
  name: devspaces-read-token
  namespace: vault-admin
spec:
  # Add fields here
  authentication: 
    path: kubernetes
    role: policy-admin
  policy: |
    # create tokens
    path "kv/rhdh-dev/dev-spaces" {
      capabilities = ["read"]
    }