apiVersion: redhatcop.redhat.io/v1alpha1
kind: VaultSecret
metadata:
  name: github-oauth-config
  namespace: openshift-devspaces
spec:
  vaultSecretDefinitions:
    - authentication:
        path: kubernetes
        role: devspaces-vault-role
        serviceAccount:
          name: default
      name: devspacesecret
      path: kv/rhdh-dev/dev-spaces
  output:
    name: github-oauth-config
    labels:
      app.kubernetes.io/part-of: che.eclipse.org
      app.kubernetes.io/component: oauth-scm-configuration
    annotations:
      che.eclipse.org/oauth-scm-server: github
      refresh: every-minute
    type: Opaque
    stringData:
      id: '{{"{{"}}.devspacesecret.id{{"}}"}}'
      secret: '{{"{{"}}.devspacesecret.secret{{"}}"}}'